name: Security Audit

on:
  schedule:
    # Run security audit daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      
    - name: Run npm audit fix (if needed)
      run: npm audit fix --dry-run
      continue-on-error: true
      
    - name: Check for known security issues
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          
          try {
            const auditOutput = execSync('npm audit --json', { encoding: 'utf8' });
            const audit = JSON.parse(auditOutput);
            
            if (audit.metadata.vulnerabilities.total > 0) {
              const summary = `🚨 **Security Audit Results**
              
              **Total Vulnerabilities**: ${audit.metadata.vulnerabilities.total}
              - Critical: ${audit.metadata.vulnerabilities.critical}
              - High: ${audit.metadata.vulnerabilities.high}
              - Moderate: ${audit.metadata.vulnerabilities.moderate}
              - Low: ${audit.metadata.vulnerabilities.low}
              
              Please review and fix these security issues.`;
              
              console.log(summary);
              
              if (audit.metadata.vulnerabilities.critical > 0 || audit.metadata.vulnerabilities.high > 0) {
                core.setFailed('Critical or high severity vulnerabilities found');
              }
            } else {
              console.log('✅ No security vulnerabilities found');
            }
          } catch (error) {
            console.log('No vulnerabilities found or audit command failed');
          }